name: compost_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  firebase_database: ^10.4.4
  cloud_firestore: 4.15.3
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  top_modal_sheet: ^2.0.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1



# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-VariableFont_wght.ttf


  uses-material-design: true
  assets:
    - images/

