// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKIKkIY6rn7J4QWMIbXHX8W39UF-lX0nA',
    appId: '1:574442334459:web:967b4a94e995ed8ef8285e',
    messagingSenderId: '574442334459',
    projectId: 'compost-19060',
    authDomain: 'compost-19060.firebaseapp.com',
    databaseURL: 'https://compost-19060-default-rtdb.firebaseio.com',
    storageBucket: 'compost-19060.appspot.com',
    measurementId: 'G-8F6KZ897ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_fy0a4kSMmmv8UZRi0uct3PfTe0sWRz0',
    appId: '1:574442334459:android:557a2c4b5c755607f8285e',
    messagingSenderId: '574442334459',
    projectId: 'compost-19060',
    databaseURL: 'https://compost-19060-default-rtdb.firebaseio.com',
    storageBucket: 'compost-19060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj9hfdv5u0fO1XYSqag8sdvwQiRe1xz_8',
    appId: '1:574442334459:ios:b6243c6439645ea1f8285e',
    messagingSenderId: '574442334459',
    projectId: 'compost-19060',
    databaseURL: 'https://compost-19060-default-rtdb.firebaseio.com',
    storageBucket: 'compost-19060.appspot.com',
    iosClientId: '574442334459-5h1nn973gltehi5mm9972pr2m3h7q65e.apps.googleusercontent.com',
    iosBundleId: 'com.example.compostTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj9hfdv5u0fO1XYSqag8sdvwQiRe1xz_8',
    appId: '1:574442334459:ios:94e3ae2603705548f8285e',
    messagingSenderId: '574442334459',
    projectId: 'compost-19060',
    databaseURL: 'https://compost-19060-default-rtdb.firebaseio.com',
    storageBucket: 'compost-19060.appspot.com',
    iosClientId: '574442334459-4uo6supsclj7h0115g3bbk9b027feqh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.compostTest.RunnerTests',
  );
}
